export enum USER_ACTION_TYPES {
  SET_CURRENT_USER = "user/SET_CURRENT_USER",
  CHECK_USER_SESSION = "user/CHECK_USER_SESSION",
  GOOGLE_SIGN_IN = "user/GOOGLE_SIGN_IN",
  EMAIL_SIGN_IN = "user/EMAIL_SIGN_IN",
  SIGN_UP = "user/SIGN_UP",
  SIGN_OUT = "user/SIGN_OUT",
}
